//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeWSSegura.MiServicioReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiServicioReference.MiServicioSoap")]
    public interface MiServicioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje HelloWorldSeguroRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldSeguro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponse HelloWorldSeguro(ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldSeguro", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponse> HelloWorldSeguroAsync(ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldSinSeguridad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorldSinSeguridad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldSinSeguridad", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldSinSeguridadAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldSeguro", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HelloWorldSeguroRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ConsumeWSSegura.MiServicioReference.AuthUser AuthUser;
        
        public HelloWorldSeguroRequest() {
        }
        
        public HelloWorldSeguroRequest(ConsumeWSSegura.MiServicioReference.AuthUser AuthUser) {
            this.AuthUser = AuthUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldSeguroResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HelloWorldSeguroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string HelloWorldSeguroResult;
        
        public HelloWorldSeguroResponse() {
        }
        
        public HelloWorldSeguroResponse(string HelloWorldSeguroResult) {
            this.HelloWorldSeguroResult = HelloWorldSeguroResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MiServicioSoapChannel : ConsumeWSSegura.MiServicioReference.MiServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiServicioSoapClient : System.ServiceModel.ClientBase<ConsumeWSSegura.MiServicioReference.MiServicioSoap>, ConsumeWSSegura.MiServicioReference.MiServicioSoap {
        
        public MiServicioSoapClient() {
        }
        
        public MiServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponse ConsumeWSSegura.MiServicioReference.MiServicioSoap.HelloWorldSeguro(ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest request) {
            return base.Channel.HelloWorldSeguro(request);
        }
        
        public string HelloWorldSeguro(ConsumeWSSegura.MiServicioReference.AuthUser AuthUser) {
            ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest inValue = new ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest();
            inValue.AuthUser = AuthUser;
            ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponse retVal = ((ConsumeWSSegura.MiServicioReference.MiServicioSoap)(this)).HelloWorldSeguro(inValue);
            return retVal.HelloWorldSeguroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponse> ConsumeWSSegura.MiServicioReference.MiServicioSoap.HelloWorldSeguroAsync(ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest request) {
            return base.Channel.HelloWorldSeguroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponse> HelloWorldSeguroAsync(ConsumeWSSegura.MiServicioReference.AuthUser AuthUser) {
            ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest inValue = new ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest();
            inValue.AuthUser = AuthUser;
            return ((ConsumeWSSegura.MiServicioReference.MiServicioSoap)(this)).HelloWorldSeguroAsync(inValue);
        }
        
        public string HelloWorldSinSeguridad() {
            return base.Channel.HelloWorldSinSeguridad();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldSinSeguridadAsync() {
            return base.Channel.HelloWorldSinSeguridadAsync();
        }
    }
}
