//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeWSSegura.MiServicioReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiServicioReference.MiServicioSoap")]
    public interface MiServicioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldSeguroResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldSeguro", ReplyAction="*")]
        ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponse HelloWorldSeguro(ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldSeguro", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponse> HelloWorldSeguroAsync(ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldSinSeguridadResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldSinSeguridad", ReplyAction="*")]
        ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadResponse HelloWorldSinSeguridad(ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldSinSeguridad", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadResponse> HelloWorldSinSeguridadAsync(ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldSeguroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldSeguro", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequestBody Body;
        
        public HelloWorldSeguroRequest() {
        }
        
        public HelloWorldSeguroRequest(ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldSeguroRequestBody {
        
        public HelloWorldSeguroRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldSeguroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldSeguroResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponseBody Body;
        
        public HelloWorldSeguroResponse() {
        }
        
        public HelloWorldSeguroResponse(ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldSeguroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldSeguroResult;
        
        public HelloWorldSeguroResponseBody() {
        }
        
        public HelloWorldSeguroResponseBody(string HelloWorldSeguroResult) {
            this.HelloWorldSeguroResult = HelloWorldSeguroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldSinSeguridadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldSinSeguridad", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadRequestBody Body;
        
        public HelloWorldSinSeguridadRequest() {
        }
        
        public HelloWorldSinSeguridadRequest(ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldSinSeguridadRequestBody {
        
        public HelloWorldSinSeguridadRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldSinSeguridadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldSinSeguridadResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadResponseBody Body;
        
        public HelloWorldSinSeguridadResponse() {
        }
        
        public HelloWorldSinSeguridadResponse(ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldSinSeguridadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldSinSeguridadResult;
        
        public HelloWorldSinSeguridadResponseBody() {
        }
        
        public HelloWorldSinSeguridadResponseBody(string HelloWorldSinSeguridadResult) {
            this.HelloWorldSinSeguridadResult = HelloWorldSinSeguridadResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MiServicioSoapChannel : ConsumeWSSegura.MiServicioReference.MiServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiServicioSoapClient : System.ServiceModel.ClientBase<ConsumeWSSegura.MiServicioReference.MiServicioSoap>, ConsumeWSSegura.MiServicioReference.MiServicioSoap {
        
        public MiServicioSoapClient() {
        }
        
        public MiServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponse ConsumeWSSegura.MiServicioReference.MiServicioSoap.HelloWorldSeguro(ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest request) {
            return base.Channel.HelloWorldSeguro(request);
        }
        
        public string HelloWorldSeguro() {
            ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest inValue = new ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest();
            inValue.Body = new ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequestBody();
            ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponse retVal = ((ConsumeWSSegura.MiServicioReference.MiServicioSoap)(this)).HelloWorldSeguro(inValue);
            return retVal.Body.HelloWorldSeguroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponse> ConsumeWSSegura.MiServicioReference.MiServicioSoap.HelloWorldSeguroAsync(ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest request) {
            return base.Channel.HelloWorldSeguroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWSSegura.MiServicioReference.HelloWorldSeguroResponse> HelloWorldSeguroAsync() {
            ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest inValue = new ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequest();
            inValue.Body = new ConsumeWSSegura.MiServicioReference.HelloWorldSeguroRequestBody();
            return ((ConsumeWSSegura.MiServicioReference.MiServicioSoap)(this)).HelloWorldSeguroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadResponse ConsumeWSSegura.MiServicioReference.MiServicioSoap.HelloWorldSinSeguridad(ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadRequest request) {
            return base.Channel.HelloWorldSinSeguridad(request);
        }
        
        public string HelloWorldSinSeguridad() {
            ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadRequest inValue = new ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadRequest();
            inValue.Body = new ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadRequestBody();
            ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadResponse retVal = ((ConsumeWSSegura.MiServicioReference.MiServicioSoap)(this)).HelloWorldSinSeguridad(inValue);
            return retVal.Body.HelloWorldSinSeguridadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadResponse> ConsumeWSSegura.MiServicioReference.MiServicioSoap.HelloWorldSinSeguridadAsync(ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadRequest request) {
            return base.Channel.HelloWorldSinSeguridadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadResponse> HelloWorldSinSeguridadAsync() {
            ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadRequest inValue = new ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadRequest();
            inValue.Body = new ConsumeWSSegura.MiServicioReference.HelloWorldSinSeguridadRequestBody();
            return ((ConsumeWSSegura.MiServicioReference.MiServicioSoap)(this)).HelloWorldSinSeguridadAsync(inValue);
        }
    }
}
